### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by garyloug**
Fix typo in udsserver_test.go

### CODE REVIEW

**Comment by garyloug** [comment]
@walshric fixing typos based on https://goreportcard.com/report/github.com/intel/afxdp-plugins-for-kubernetes

The report here seems outdated. The code only contained one of the reported typos. Any idea why this is happening? The Go report on my end here says `Last refresh: now`.

@patrickog11 - any idea?

**Review by patrickog11 — APPROVED** [review]

**Comment by garyloug** [comment]
@walshric it looks like the scorecard looks at the latest tag (v0.0.2 in our case) rather than latest code on main. All but one of the typos were already fixed. This PR fixes the last one.

**Review by walshric — APPROVED** [review]
perfect

**Review by walshric — APPROVED** [review]
looks good

**Pull request merged**
