### PR TITLE
ci-build: update dependencies

### PR DESCRIPTION
**Pull request by maryamtahhan**
Update ci dependencies to be able to build the upcoming Kind support.

### CODE REVIEW

**Comment by maryamtahhan** [comment]
Needed to be able to build https://github.com/intel/afxdp-plugins-for-kubernetes/pull/46

**Comment by maryamtahhan** [comment]
@garyloug can we review and merge if all is ok? so that we can rebuild the kind PR?

**Review by garyloug — APPROVED** [review]

**Comment by garyloug** [comment]
hey @maryamtahhan approved. Some of the CI jobs appear to be hung, just trying to fix this... Won't let me merge until they pass.

**Comment by maryamtahhan** [comment]
> hey @maryamtahhan approved. Some of the CI jobs appear to be hung, just trying to fix this... Won't let me merge until they pass.

no worries - thank you

**Comment by maryamtahhan** [comment]
Super, thank you @garyloug

**Pull request merged**
